### ISSUE TITLE
Collaborator Info

### ISSUE THREAD

**Issue by jklmnn** [jklmnn/unilinks#12]
@lutzbox ich hab dich mal als Collaborator hinzugefügt, da du das ja aktuell hauptsächlich maintainst, übrigens danke dafür ;)
Die Webseite nutzt die Git Tags um die aktuelle Version herauszufinden. Ich hab das Schema der Versionierung der Tags im [Wiki](https://github.com/jklmnn/unilinks/wiki/Tag-versioning) beschrieben. Wenn du eine Änderung online bringen willst kannst du die einfach mit z.Bsp. `git tag -a 18.w.1 -m "Wintersemester 18 Version 1"` taggen.
Du kannst das Issue schließen, wenn du es gelesen hast.

**Comment by lutz** [comment]
Ja das mit dem maintainen mache ich ja auch weil mein Tool die Github Infos von deinem Repo abzweigt XD aber kein Thema. Allerdings hätte ich noch eine Frage. Den Befehl `git tag` muss ich den nach dem Sync ausführen? (Aso Commit, Push, Tag) das die Änderung nicht nur im Netz ist, sondern das die Gitub Page die Änderung anzeigt?

**Comment by jklmnn** [comment]
Die Tags sind quasi wie Commits. Wenn du einen Tag erstellst ist der erst mal nur lokal da. Du musst den dann explizit zu origin pushen:
```
$ git tag -a <tag id>
$ git push origin <tag id>
```
Wenn der Tag gepusht ist zieht die Seite den automatisch (sie lädt einfach alle Tags über die GitHub API und den letzten nutzt sie dann um den Content über Rawgit zu adressieren).

**Comment by lutz** [comment]
Alles klaro, habe es jetzt mal über das GitHub Web Interface gemacht, da ging es schon mal soweit!
