### ISSUE TITLE
Erweiterung der Unilinks

### ISSUE THREAD

**Issue by lutz** [jklmnn/unilinks#15]
Die Frage die sich mir stellt ist, ob wir Mikroelektronik als Vertiefung raus nehmen und statt dessen Mechtronik und RES noch aufnehmen. Ich könnte bei den STUKOs mal anfragen ob da Bedarf besteht.

Außerdem würde ich mir mal die Mühe machen das Json Grundgerüst bei alle dann gleich zu machen (also das über all auch das Modul entsprechend steht usw.

Was hältst du davon?

**Comment by lutz** [comment]
Den Teil Allgemein könnte mann dann auch bei Elektrotechnik und ggf. den neuen auch anzeigen!

**Comment by jklmnn** [comment]
Das können wir gerne machen. Ich hatte die Vertiefungen mal reingenommen weil die jemand gemacht hat und da sage ich nicht nein ;)
Prinzipiell fänd ich es aber auch besser wenn man einfach alle Studiengänge da drin stehen hat. Vor allem den allgemeinen Teil und das Grundstudium (gibts in der ET eigentlich auch Bachelor/Master?). Vertiefungen gibt es zu viele und die Leute für die das wichtig ist finden die richtigen Sachen schon. Man könnte vielleicht eine Übersichsseite dafür verlinken, falls es sowas gibt.

Wenn alle Einträge Modulnummern haben könnte man die auch mit in der Liste anzeigen.

Generell finde ich es super, dass das jemand weiter macht :+1:.
Aber ich muss auch dazu sagen, dass ich, da ich bald fertig bin, nicht die Zeit habe mich um viel Inhaltliches zu kümmern, du hast dahingehend ziemlich freie Hand ;)

**Comment by lutz** [comment]
Das sind alles Diplom Studiengänge:
![image](https://user-images.githubusercontent.com/26437097/46720852-e7f89980-cc71-11e8-81ce-9ecc7eb00cb1.png)
Bei IST würde ich es bis zum 6. Semester lassen, da ja bis dorthin noch allgemeine Pflichtveranstaltungen gibt. Bei ET auf jeden Fall das Grundstudium. Ob es im Hauptstudium noch allgemeine Pflicht Veranstaltungen gibt weiß ich nicht. Die anderen Studiengänge kenne ich sonst gar nicht. Übersichtsseite zur Vertiefung mit Links gibt es soweit ich weiß nicht. 

Generell könnte man überlegen, das Projekt auf einen eigenen GitHub Account zu lagern, dass es losgelöst von Personen ist. Dann könnte man das Projekt auch an nachfolgende Generationen weitergeben. Ich habe auch so ein kleines C# Projekt nebenherlaufen um unter windows 10 ne direkte IST Anbindung zu haben

![image](https://user-images.githubusercontent.com/26437097/46721137-9bfa2480-cc72-11e8-8e39-86d4ab2e18fe.png)

Das könnte man dahingehend noch erweitern und dort aufnehmen. Könntest du Mikroelektronik rausnehmen und auch im Source Code alle Dateien löschen die aktuell nicht genutzt werden? Da gibt es ja auch noch Unterscheidungen zu GS und HS (et.gs.json usw)

**Comment by lutz** [comment]
P.S. Das Notenberechnen Teil würde ich auch raus nehmen.

**Comment by jklmnn** [comment]
Das Berechnen der Noten kam mit den Vertiefungen in #1 dazu. Das sollte irgendwann mal auf der Seite sein aber dazu hab ich nie Zeit gefunden.

Die Idee mit der Organisation finde ich gut, aus dem gleichen Grund läuft das ja aktuell als GitHub Page und nicht mehr auf meinem Server. Man könnte sogar über eine eigene Domain nachdenken ;)

Ich hab zwar Grundstudium gesagt aber eigentlich meinte ich Pflichtveranstaltungen ;) Ich kenne mich da halt leider nur mit IST wirklich aus, bei den anderen Studiengängen kann ich mich auch nur vor Google setzen.

**Comment by lutz** [comment]
Gut da könnte ich bei den Stukos nach fragen ob jemand Bock hätte da die Links rauszusuchen und bissel Licht ins Dunkeln zu bringen. Eigentlich wollte ich das Projekt gern beim FSR ansiedeln, aber da kam nicht viel zurück. Das mit dem GitHub-Pages finde ich gar nicht so schlecht, weil kostenlos.  Der Code für das Notenberechnen ja dann halt in ein eigenes Projekt kommt. Ich habe das allerdings noch nie getestet. Wobei mann auch noch schauen müsste wenn es bei GitHub bliebt, was für einen aussagekräftigen Benutzernamen man findet

**Comment by jklmnn** [comment]
Ich werde bei Gelegenheit mal eine Organisation gründen. Da kann man dann alles hinmigrieren. Da kann man sich dann auch später noch entscheiden wer das leiten soll. Außerdem sollte es trotzdem immer offen bleiben.

**Comment by lutz** [comment]
Das auf jeden Fall. Das ist auch nichts was man irgendwie geschlossen halten muss.

**Comment by jklmnn** [comment]
Ich wollte grad eine Orga erstellen, aber der Nutzername unilinks ist schon vergeben. Fällt dir was sinnvolles ein?

**Comment by lutz** [comment]
Ja Namensfindung ist echt schwer, weil fast alles vergeben ist: irgend so was allgemeines wie

### **[UPDATE 18.10.2018]**

- devboxsolutions
- tudlink (TUD Links)
- unilinkproject

**Comment by lutz** [comment]
Ich habe mir noch ein paar Gedanken gemacht über die wir vielleicht in diesem Zuge noch nachdenken könnten. Grundsätzlich stelle ich mir aktuell 3 Projekte vor:

**unilinks.core**
Das beinhaltet sämtlich JSON Dateien die für die einzelnen Studiengänge gibt.
- gs.json (Allgemein)
- ist.gs.json (IST Grundstudium)
- ist.hs.json (IST Hauptstudium)
- et.gs.json  (ET Grundstudium)
- et.hs.it,json (ET Hauptstudium Vertiefung Informationstechnik Pflichtfächer)
usw.

Die ET'ler haben im 5.-6. Semester je nach Vertiefung auch Pflichtfächer die belegt werden müssen. Wir würden quasi wie jetzt dann den Wahlpflichtbereich weglassen. Alle JSON Dateien haben den selben Aufbau wobei bei den Links zu den Fächern folgendes drin steht:

name: ET 1
modul-id: ET-3746734-22
modul-name: Grundlagen der Elektrotechnik (Bei Systemtheorie z.B.  Systemtheorie und Automatisierungstechnik)
link: http:/...

Das wäre dann quasi die Datengrundlage.

**unilinks.shell.web**
Das wäre wie jetzt die Webseite die man im Browser aufrufen kann. Ich stelle mir so die Möglichkeit vor das man das konfigurieren kann über Parameter so das sman sagen kann ich generiere einen statischen Link der mir aktuell nur Allgemein und Grundstudium anzeigt oder später dann nur die Vertiefung. Dann würde der Link angezeigt mit Name vielleicht im Klammern die Modul-ID und als Tooltipp der richtige Modulname) Außerdem könnte ich mir vorstellen neben dem Webseitenlink auch einen Datenlink zu genieren der je nach Parameterwahl dann ein gültiges JSON Objekt zurück gibt, dass dann die gewählten Informationen anzeigt.

**unilinks.shell.win**
Das könnte dann mein kleines Tool sein um sich in der Taskleiste die Links anzeigen lassen zu können. Das nutzt dann den generierten Datenlink aus dem oberen Projekt. Im Moment läuft es nur Windows 10. Eventuell finde ich die Zeit das zu entschlacken und dann bis Windows 7 zu unterstützen. Wenn irgendjemand Kreatives mal Lust hat kann er ja auch für andere OS Systeme was bauen.

In wie weit die einzelnen Punkte umsetzbar sind würde ich gern diskutieren. Muss gestehen dass ich von Webentwicklung nicht so viel Ahnung habe, aber wir können ja mal schauen. Grundsätzlich finde ich es gut wenn Lizenztechnisch das jeder nutzen kann, würde mich aber freuen wenn Verbesserungen auch zurück ins Originalrepository gespielt werden.

Was hältst du davon @jklmnn ?

**Comment by jklmnn** [comment]
Sorry für meine späte Antwort, ich hatte nach wie vor keinen sinnvollen Namen. Also ich würde diesbezüglich schon etwas nehmen, was thematisch den Inhalt der Organisation wiederspiegelt und nicht zu allgemein ist.

Die Aufteilung der von Daten und Webanwendung finde ich sinnvoll. Einerseits erleichtert das den Zugriff (oder notfalls auch mal die Migration der Daten) und andererseits macht es die Lizensierung leichter, da sich Daten und Code da unterschiedlich verhalten.
Apropos: Die Daten würde ich weiterhin unter die Unlicense stellen. Ich sehe darin keine Schöpfungshöhe und zusammengesucht haben wir sie ja selbst. Die Webanwendung (ich gehe mal davon aus, dass wir einfach die GH-Page migrieren)  würde ich gerne unter AGPLv3 stellen. Ich sehe keinen Grund warum das jemand selbst closed source hosten wollen bzw. können sollte.
Ich glaube nicht, dass wir erzwingen können, dass Aktualisierungen der Daten zurück zu uns kommen. Aber für die Webanwendung sollte die AGPL diesen Zweck hinreichend erfüllen.

Das Konzept zu den Daten finde ich sinnvoll. Inwieweit eine Aufteilung von Grund- und Hauptstudium notwendig ist weiß ich nicht, das würde ich evtl. zusammen nehmen. Andererseits könnte man so evtl. auch Redundanzen sparen (vor allem im Bezug auf die allgemeinen Links)

Was die Webseite betrifft, ich betrachte das jetzt mal im Kontext der GitHub-Pages, da man es sonst extern hosten müsste. Ein Link der die gewünschten Teile der Seite anzeigt müsste das in den Parametern tun und das per JavaScript machen. Wir haben nicht die Möglichkeit serverseitiger Auswertungen.
Das Betrifft insbesondere den API Link. So wie du das beschrieben hast wird das mit GH-Pages definitiv nicht funktionieren, da das serverseitig generiert werden müsste. Wenn man die Daten in einer eigenen Anwendung nutzen will müsste man das analog zur Webanwendung bauen. Also GH-API aufrufen, letzten Tag holen, Links für RawGit generieren und dann abrufen.

Zu dem Windowstool kann ich keine Aussage treffen, da ich kein Windows nutze. Generell war das initiale Ziel der Seite so einfach und schnell auf allen Geräten verfügbar zu sein wie möglich. Da die Hauptaufgabe ist/war die Links bereitzustellen war der Browser auch die naheliegende Plattform. Da du ja noch zusätzliche Funktionalität bereitstellen willst ist eine externe Anwendung evtl. sicher sinnvoll, aber das überlasse ich dir.

**Comment by lutz** [comment]
> Sorry für meine späte Antwort, ich hatte nach wie vor keinen sinnvollen Namen. Also ich würde diesbezüglich schon etwas nehmen, was thematisch den Inhalt der Organisation wiederspiegelt und nicht zu allgemein ist.

Kein Problem, dass ist ja nichts was eilt.  Das stimmt schon, die Frage ist ob es einen Namen gibt der den Inhalt wiederspiegelt aber noch nicht vergeben ist. Ich dachte auch etwas zur Uninähe aber das wird vielleicht dann auch wieder Problematisch wie TUDBox oder so, weil es ja nichts offizielles ist. **ETITLinks** für Elektrotechnik und Informationstechnik Links steht oder sowas. Mhmm schwierig.....

Ich fand die Idee mit der Aufteilung nett, da dass dann wirklich spezifisch geordnet ist. Gerade bei der ET im Hauptstudium. Im Grundstudium bekommen alle Vertiefung dann halt den Block **Allgemeines**, den Block **Grundstudium** und dann je nach Vertiefung.  Das mit dem  Windowstool habe ich nur eingebracht weil es ja schlussendlich nur eine GUI ist die die links anzeigt. Die meisten werden die Webseite nehmen.  Wenn wir es un ganz einfach machen wollen, bleiben wir für die Webseite beim Tag System sowie du es ja jetzt im Moment auch machst und protokollieren einfach in einem Wikieinträge alle verfügbaren GitRaw Links für das Konsumieren der Daten via JSON Object für eine Anwendung wie dieses Tool.  Im Moment hole ich mir ja die Daten über den direkten RAW Link und Werte die Tags überhaupt nicht aus.

**Comment by lutz** [comment]
Ich habe mal im dev-branch angefangen alle Dateien mit dem gleichen Aufbau des JSON Model anzulegen, das kann mann ja dann entwickeln!

**Comment by lutz** [comment]
Ich habe mal weiter oben angefangen in einem Beitrag Namensideen zu sammeln...

**Comment by jklmnn** [comment]
So, ich hab eine orga (https://github.com/tudlinks) mit zwei repos erstellt und die entsprechenden commits auf die repos verteilt. man müsste fürs erste nur noch alle links und die readmes anpassen.

**Comment by lutz** [comment]
Den dev Branch hattest du nicht mitgezogen oder? Naja kann ich ja noch erledigen. Ich würde das aktuelle Repo bei deinem Account gerne so lange lassen bis wir mit dem neuen Projekt sind. So viele Änderungen werden dieses Semester bestimmt nicht mehr kommen. Was hältst du von der Idee die Daten auf die verschiedene Json Files zu verteilen so wie ich es im dev Branch gemacht hatte

**Comment by lutz** [comment]
Den dev Branch hattest du nicht mitgezogen oder? Naja kann ich ja noch erledigen. Ich würde das aktuelle Repo bei deinem Account gerne so lange lassen bis wir mit dem neuen Projekt sind. So viele Änderungen werden dieses Semester bestimmt nicht mehr kommen. Was hältst du von der Idee die Daten auf die verschiedene Json Files zu verteilen so wie ich es im dev Branch gemacht hatte

**Comment by jklmnn** [comment]
https://github.com/tudlinks/data/tree/dev done.

Ich würde gerne so zeitig wie möglich migrieren, da jede Änderung die wir in meinem eigenen Repo machen zusätzlich migriert werden muss. Ich würde die Seite der Organisation parallel aufbauen, sodass wir zwei identische parallele Instanzen haben und dann muss man nur noch alle links ändern.

Prinzipiell finde ich es sinnvoll, das in logische Teilbereiche zu trennen. Allerdings ist das so wie es jetzt ist nicht kompatibel zur Webseite, da die Dateinamen aus den Datem in Index abgeleitet werden und das jetzt nicht mehr funktioniert. Man müsste da evtl. den Index und analog die Webseite anpassen.
Außerdem sind die Dateinamen unkonsistent, einmal `gl.ist.json` und einmal `ist.gs.json`. Ich würde ein Schema `Teilbereich.Studiengant.json` vorschlagen.

**Comment by lutz** [comment]
Ja das mit der Inkonsistenz habe ich natürlich bemerkt. Bei IST, MT, RES wäre dass dann

gs.ist.json
hs.ist.json
gs.mt.json
hs.mt.json
gs.res.json
hs.res.json

Die Frage ist wie wir das bei ET machen dadurch das sie im HS ja eine Abhängigkeit von ihrer Vertiefung haben
gs.et.json

aber dann bei hs.eet|gem|...json? 

Wir können sowohl ja beim data Projekt als auch beim Webseiten Projekt im dev entwickeln und der master Branch ist dann halt der aktuelle Stand.

**Comment by lutz** [comment]
Und für den allgemeinenteil dann

gl.ist.json usw?

**Comment by lutz** [comment]
Ich überlege ob wir die Organisation nicht eher unilinksproject nennen weil wir sonst von tudlinks und einmal von unilinks sprechen einfach dass das ähnlicher zu einander ist.

**Comment by jklmnn** [comment]
Ich würde den Allgemeinen Teil gar nicht trennen. Die zwei Links die bei IST extra sind, egal das kann der Rest auch sehen.
Na das wäre dann `(eet|gem).hs.et.json`. Das Hauptstudium ist schließlich der Vertiefung übergeordnet.
Generell finde ich einen extra dev-Branch sinnvoll.

Ich hab die Organisation umbenannt: https://github.com/unilinksproject.

**Comment by lutz** [comment]
Ja das finde ich gut, dann hätten wir jetzt folgende Dateistruktur

- index.json
- gl.json
- gs.ist.json
- gs.et.json
- gs.mt.json
- gs.res.json
- hs.ist.json
- hs.mt.json
- hs.res.json
- amr.hs.et.json
- eet.hs.et.json
- gmmhs.et.json
- iths.et.json
- mehs.et.json

Soweit ich das sehe müsste ich Mitglied der Organisation werden und du mir dann die Schreib-/Leserechte für die Projekte geben, dann kann ich es Clonen und entsprechend anpassen. Das JSON Objekt würde ich die Credits rausnehmen, weil das manchmal schwierig ist zu verteilen

```
{
 "name": "Mathe 1",
 "url": "http://www.math.tu-dresden.de/~wensch/mainfiles/?page=mathe1",
"modul": "Algebraische und analytische Grundlagen",
"modul-id": "ET-01 04 01"
},
```

Bei den allgemeinen Teil würde ich sagen dass wir nur

```
{
 "name": "Universitätssport",
 "url": "..."
},
```

nehmen.

**Comment by jklmnn** [comment]
Ich dachte ich hätte dich eingeladen? Ich hab dich jetzt nochmal eingeladen, vllt hat das wegen dem umbenennen nicht geklappt.

Die Strukturen sehen in Ordnung aus. Wofür steht eigentlich das `gl` bei den allgemeinen Sachen?

**Comment by lutz** [comment]
Jetzt kam der Einladungslink an. Ich dachte irgendwie an gl = general oder sowas. Ich kann es auch ag = allgemein oder so nennen

**Comment by jklmnn** [comment]
Naja, da ja eh alles Deutsch ist kann man das auch Deutsch nennen. Nenne es doch `allg` dann ist alles klar ;)

**Comment by lutz** [comment]
Bei der aktuellen Dateinamenskonvention `Teilbereich.Studiengant.json`  überlege ich auch ob wir das nicht drehen um die Sortierung auf Dateiebene  zu erleichtern und alle zu einem Studiengang zugehörige Dateien zusammen zu haben: `Studiengang.Teilbereich.Vertiefung.json`

- [x] Dateinamen anpassen

**Comment by lutz** [comment]
[Pflichtmodule des Diplomstudienganges ET](https://docs.google.com/spreadsheets/d/1z6GIkftqk-3GuwxOV2_lR65wY1h-8RmtyM0FVJMSxZ0/edit?usp=sharing)
[Pflichtmodule des Diplomstudienganges IST](https://docs.google.com/spreadsheets/d/14NnXlFO_TvIzs5a_bDnZ1UiqfMWf0XE2L2QtmqwBErs/edit?usp=sharing)
[Pflichtmodule des Diplomstudienganges MT](https://docs.google.com/spreadsheets/d/1_lqEkMLCE_2StQXufbZFef5I98iKqlnz9TOR0aUBLiM/edit?usp=sharing)
[Pflichtmodule des Diplomstudienganges RES](https://docs.google.com/spreadsheets/d/1nJwtD5rTxAc442EfJSi_PCXlYBXX7MdQbp9_LODoNFg/edit?usp=sharing)

Ich habe mal angefangen Übersichten zu erstellen welcher Studiengang welche Pflichmodule beinhaltet!

**Comment by lutz** [comment]
Ich würde, jetzt das letzte Issue hier schließen und alles weitere wird dann in den neuen Projekten (-boards)  geklärt!
