### ISSUE TITLE
Änderungsvorschläge für IST

### ISSUE THREAD

**Issue by lutz** [jklmnn/unilinks#4]
Hallo hier ein paar Änderungsvorschläge für IST im Abschnitt Allgemein

[Umbenennung] Studierenen-Portal -> Selma
Stundenpläne
Hisqis
Prüfungsamt
jExam
Opal
[Umbenennung] Prüfungsordnung -> Studiendokumente [Neuer Link] https://tu-dresden.de/ing/elektrotechnik/studium/beratung-und-service/studiendokumente-und-ordnungen/diplom-ist
[Umbenennung]Fachschaftsrat ET -> Fachschaftsrat
 [Umbenennung] AGDSN -> AG DSN
Auditorium
Mensa
netaction
Cloud
Cloud Passwort

Außerdem wäre es vielleicht gut die Links zu ergänzen

MSX (https://msx.tu-dresden.de/)
Campus Navigator (https://navigator.tu-dresden.de/)
Campus Sachsen (Office 365) (https://campussachsen.tu-dresden.de/)
SLUB (http://www.slub-dresden.de/startseite/)
MS Imagine (https://e5.onthehub.com/WebStore/ProductsByMajorVersionList.aspx?cmi_cs=1&cmi_mnuMain=bdba23cf-e05e-e011-971f-0030487d8897&ws=0dc00773-839b-e011-969d-0030487d8897&vsro=8)

Gruß

**Comment by jklmnn** [comment]
Danke, ich werde mir das bei Gelegenheit genauer anschauen, sollte aber zu machen sein ;)

**Comment by jklmnn** [comment]
Ich habe Office 365 und MS Imagine außen vor gelassen, da ich die Nutzung dieser Software im Studium nicht unterstützen kann.
